plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sajad.anbaryar'
    compileSdk 34

    defaultConfig {
        applicationId 'com.sajad.anbaryar'
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName '1.1'
    }

    signingConfigs {
        release {
            storeFile file('anbaryar.jks')
            storePassword 'anbaryar1405'
            keyAlias 'anbaryar'
            keyPassword 'anbaryar1405'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.11.0'
    implementation 'androidx.core:core:1.13.1'
}
